try pipx instead of pip
default: commands[0]> pytest -rFEx --durations 10 --color yes -n auto
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: -n
  inifile: /home/runner/work/honegumi/honegumi/pytest.ini
  rootdir: /home/runner/work/honegumi/honegumi